version: '2'

services:

  nginx:
    build: ./nginx
    image: "dendrapreview:nginx"
    restart: always
    depends_on:
      - noaa-nws-api
      - web-api
    ports:
      - "${WEB_ADMIN_PORT}:8088"
      - "${WEB_PORT}:80"

  influxdb-erczo:
    build: ./influxdb
    image: "dendrapreview:influxdb-erczo"
    restart: always
    ports:
      - "${ERCZO_INFLUXDB_PORT}:8086"
    environment:
      - INFLUXDB_META_DIR=/influxdb/meta
      - INFLUXDB_DATA_DIR=/influxdb/data
      - INFLUXDB_DATA_WAL_DIR=/influxdb/wal
    volumes:
      - "${ERCZO_INFLUXDB_VOLUME}"

  influxdb-ucnrs:
    build: ./influxdb
    image: "dendrapreview:influxdb-ucnrs"
    restart: always
    ports:
      - "${UCNRS_INFLUXDB_PORT}:8086"
    environment:
      - INFLUXDB_META_DIR=/influxdb/meta
      - INFLUXDB_DATA_DIR=/influxdb/data
      - INFLUXDB_DATA_WAL_DIR=/influxdb/wal
    volumes:
      - "${UCNRS_INFLUXDB_VOLUME}"

  mongo:
    build: ./mongo
    image: "dendrapreview:mongo"
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_APPDB_USERNAME
      - MONGO_APPDB_PASSWORD
      - MONGO_APPDB_DATABASE
    volumes:
      - ./mongo-initdb:/docker-entrypoint-initdb.d
      - "${MONGO_DB_VOLUME}"

  nats-streaming:
    build: ./nats-streaming
    image: "dendrapreview:nats-streaming"
    restart: always
    ports:
      - "${STAN_PORT}:4222"
      - "${STAN_MONITOR_PORT}:8222"
    volumes:
      - "${STAN_VOLUME}"

  noaa-nws-api:
    image: "dendra/dendra-noaa-nws-api@sha256:f7450c6fa727c43ac94b37fdcde1acb548f969da709e0d8fa4a25fe4b5a5a5e7"
    restart: always

  web-api:
    image: "dendra/dendra-web-api:preview"
    restart: always
    depends_on:
      - mongo
    environment:
      - AGGREGATE_DISPATCH_API_URL=http://dispatch-api:8080
      - AGGREGATE_JSON_API_URL=http://aggregate-json-api:8080
      - ANNOTATION_DISPATCH_API_URL=http://dispatch-api:8080
      - DEFAULT_INFLUXDB_API_URL=http://influxdb:8086
      - ERCZO_INFLUXDB_API_URL=http://influxdb-erczo:8086
      - UCNRS_INFLUXDB_API_URL=http://influxdb-ucnrs:8086
      - LEGACY_MYSQL_URL
      - MONGO_URL=mongodb://${MONGO_APPDB_USERNAME}:${MONGO_APPDB_PASSWORD}@mongo:27017/${MONGO_APPDB_DATABASE}
      - NOAA_NWS_API_URL=http://noaa-nws-api:8080
      - WEB_API_SECRET
    volumes:
      - ./web-api-config:/home/node/app/config
